#
# Manifest module for 'Harden Sysvol'
#
# Generated by : Mehdi Dakhama
#
# Generated : 11/2024

@{
    # ID du module
    RootModule        = 'HardenSysvol.psm1'

    # Infos du module
    ModuleVersion     = '1.7.0'
    GUID              = '31c02f99-d8aa-4996-8c55-647041bd7bbf'
    Author            = 'DAKHAMA Mehdi'
    CompanyName       = 'HardenAD'
    Copyright         = '(c) 2024 DAKHAMA Mehdi. All rights reserved.'
    Description       = 'Harden Sysvol is a Powershell Module to scan sysvol folder to search the sensitivity data, and vulnerability.'
    PowerShellVersion = '5.1'
    
    # Dépendances
    RequiredModules = @(@{
            ModuleVersion = '0.0.180'
            ModuleName    = 'PSWriteHTML'
            Guid          = 'a7bdf640-f5cb-4acf-9de0-365b322d245c'
        },  @{
            ModuleVersion = '0.2.0'
            ModuleName    = 'PSWriteOffice'
            Guid          = 'd75a279d-30c2-4c2d-ae0d-12f1f3bf4d39'
        })

    FunctionsToExport = @('Invoke-Hardensysvol')

    CmdletsToExport = @()

    VariablesToExport = '*'

    AliasesToExport = @()

    PrivateData = @{

    PSData = @{

        Tags = @('HardenSysvol','AuditAD','AuditNetlogon','AuditSysvol','ActiveDirectory','Security','Vulnerability')

        LicenseUri = 'https://github.com/dakhama-mehdi/Harden-Sysvol/blob/main/LICENSE'

        ProjectUri = 'https://github.com/dakhama-mehdi/Harden-Sysvol'

        IconUri = "https://github.com/dakhama-mehdi/Harden-Sysvol/blob/main/Pictures/HardenSysvol.png?raw=true"
			
		ReleaseNotes  = @'
        1.7.0 : Add check 7Z,Rar protected by password if 7zip is installed
        1.6.8 : Revise all magic number and add more total about 180 magic number
        1.6.7 : Add check db files, add check signing msu,cab, add check keepass files
                Add check zip protected by password
        1.6.6 : Fix score
        1.5.0 : Support certificat cer,der,pam,p7b 
                Add Json file - Extensions binary
		1.4.0 : Add new options : Add/Remove Pattern - Add/Remove Extension
			    Check ZIP/RAR
        1.3.0 : Support PPTX, ODP, Detect MD5,SHA1,SHa256, IPv4
        1.2.0 : Version Beta (Fix double result)
        1.1.0 : Fix dependence model error
        1.0.0 : Version Test
'@
    } 
} 
    HelpInfoURI = 'https://github.com/dakhama-mehdi/Harden-Sysvol/tree/main/Docs'

}
